=== aeclipsia/marcas3a/xpath/ejercicio4.dtd
<!ELEMENT agencia (nombre,web,viajes)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT viajes (viaje+)>
<!ELEMENT viaje (nombre,precio,salida)>
<!ATTLIST viaje id NMTOKEN #REQUIRED>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT salida EMPTY>
<!ATTLIST salida mes NMTOKEN #REQUIRED>

=== aeclipsia/marcas3a/xpath/ejercicio4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agencia SYSTEM "ejercicio4.dtd">
<agencia>
  <nombre>Weroad</nombre>
  <web>https://www.weroad.es/</web>
  <viajes>
    <viaje id="balijun">
      <nombre>Bali 360</nombre>
      <precio>799</precio>
      <salida mes="junio" />
    </viaje>
    <viaje id="srijul">
      <nombre>Sri Lanka 360 summer</nombre>
      <precio>999</precio>
      <salida mes="julio" />
    </viaje>
    <viaje id="panago">
      <nombre>Panam√°</nombre>
      <precio>1780</precio>
      <salida mes="agosto" />
    </viaje>
    </viajes>
</agencia>
