=== aeclipsia/marcas3a/xml/01_persona.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,(mujer|hombre),fecha_de_nacimiento,ciudad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mujer EMPTY>
<!ELEMENT hombre EMPTY>
<!ELEMENT fecha_de_nacimiento (dia,mes,anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>

=== aeclipsia/marcas3a/xml/01_persona.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE personas SYSTEM "01_persona.dtd">
<personas>
   <persona>
      <nombre>Elsa</nombre>
      <mujer/> 
      <fecha_de_nacimiento>
        <dia>18</dia>
        <mes>6</mes>
         <anio>1998</anio>
      </fecha_de_nacimiento>
      <ciudad>Pamplona</ciudad>
   </persona>
   <persona>
      <nombre>Rodrigo</nombre>
      <hombre/> 
      <fecha_de_nacimiento>
        <dia>3</dia>
        <mes>1</mes>
         <anio>1998</anio>
      </fecha_de_nacimiento>
      <ciudad>Murcia</ciudad>
   </persona>
</personas>
