=== aeclipsia/marcas3a/dtd/Ejercicio2.dtd
<!ELEMENT ciudades (ciudad+)> <!--  ciudad con '+' porque hay mÃ¡s de 1 ciudad -->
<!ELEMENT ciudad (nombre,capital?)> <!-- tiene que haber un '?' en el capital ya que no es obligatorio -->
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT capital EMPTY>

=== aeclipsia/marcas3a/dtd/Ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ciudades SYSTEM "Ejercicio2.dtd">
<ciudades>
<ciudad>
<nombre>Buenos Aires</nombre>
<capital/>
</ciudad>
<ciudad>
<nombre>Liverpool</nombre>
</ciudad>
<ciudad>
<nombre>Osaka</nombre>
</ciudad>
<ciudad>
<nombre>Oslo</nombre>
<capital/>
</ciudad>
</ciudades>
