=== aeclipsia/marcas3a/dtd/Ejercicio8.dtd
<!ELEMENT libro-recetas (receta)+>
<!ELEMENT receta (titulo, ingrediente+, preparacion,truco?)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT preparacion (#PCDATA)>
<!ELEMENT truco (#PCDATA)>

=== aeclipsia/marcas3a/dtd/Ejercicio8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libro-recetas SYSTEM "Ejercicio8.dtd">
<libro-recetas>
    <receta>
        <titulo>Huevo Frito</titulo>
        <ingrediente>Huevo</ingrediente>
        <ingrediente>Aceite</ingrediente>
        <preparacion>Cocinalo</preparacion>
        <truco>Pon sal</truco>
    </receta>
    <receta>
        <titulo>Cafe</titulo>
        <ingrediente>Café</ingrediente>
        <ingrediente>Agua caliente</ingrediente>
        <preparacion>Mezcla café con agua</preparacion>
    </receta>
</libro-recetas>
