=== aeclipsia/marcas3a/xslt/14ejemploimagen.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT web (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT libro (titulo, imagen?, autor+, anio, precio, web?)>
<!ATTLIST libro
	categoria (diseño | filosofía | informática | juvenil | distopía | novela) #REQUIRED
>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ATTLIST titulo
	idioma (fr | ing | sp) #REQUIRED>
<!ELEMENT libreria (libro+)>

=== aeclipsia/marcas3a/xslt/14ejemplobiblioimagen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "14ejemploimagen.dtd">
<?xml-stylesheet type="text/xsl" href="14ejemploimagen.xsl"?>
<libreria>
	<libro categoria="juvenil">
		<titulo idioma="ing">Harry Potter</titulo>
		<imagen>HarryPotter.jpg</imagen>
		<autor>J K. Rowling</autor>
		<anio>2005</anio>
		<precio>29.99</precio>
		<web>https://es.wikipedia.org/wiki/Harry_Potter</web>
	</libro>
	<libro categoria="novela">
		<titulo idioma="sp">El origen perdido</titulo>
		<autor>Matilde Asensi</autor>
		<anio>2003</anio>
		<precio>20</precio>
		<web>https://es.wikipedia.org/wiki/El_origen_perdido</web>
	</libro>
	<libro categoria="distopía">
		<titulo idioma="ing">Los juegos del hambre</titulo>
		<autor>Suzanne Collins</autor>
		<anio>2008</anio>
		<precio>19.99</precio>
	  </libro>
	<libro categoria="filosofía">
		<titulo idioma="fr">Sobre la felicidad</titulo>
		<autor>Frédéric Lenoir</autor>
		<anio>2014</anio>
		<precio>16.90</precio>
	</libro>
	<libro categoria="novela">
		<titulo idioma="sp">El señor de las moscas</titulo>
		<imagen>moscas.jpeg</imagen>
		<autor>William Golding</autor>
		<anio>1972</anio>
		<precio>9.95</precio>
	</libro>
	<libro categoria="informática">
		<titulo idioma="sp">XQuery</titulo>
		<autor>James McGovern</autor>
		<autor>Per Bothner</autor>
		<autor>Kurt Cagle</autor>
		<autor>James Linn</autor>
		<autor>Vaidyanathan Nagarajan</autor>
		<anio>2003</anio>
		<precio>49.99</precio>
	</libro>
	<libro categoria="diseño">
		<titulo idioma="sp">Aprender Ilustrator CC</titulo>
		<autor>Media active</autor>
		<anio>2014</anio>
		<precio>17.90</precio>
	</libro>
	<libro categoria="distopía">
		<titulo idioma="ing">Balada de pájaros cantores y serpientes</titulo>
		<autor>Suzanne Collins</autor>
		<anio>2020</anio>
		<precio>27.90</precio>
		<web>https://www.casadellibro.com/libro-balada-de-pajaros-cantores-y-serpientes/9788427220287/11380135</web>
	  </libro>
</libreria>
